# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{ config, lib, modulesPath, ... }:

{
  imports =
    [
      (modulesPath + "/installer/scan/not-detected.nix")
    ];

  networking.hostId = "4488bd1a";
  networking.hostName = "telchar";
  boot = {
    initrd.availableKernelModules = [ "nvme" "xhci_pci" "thunderbolt" "usbhid" "usb_storage" "sd_mod" ];
    initrd.kernelModules = [ "amdgpu" ];
    kernelModules = [ "kvm-amd" ];
    extraModulePackages = [ ];
  };

  swapDevices = [ ];
  virtualisation.docker.enable = true;

  hardware.cpu.amd.updateMicrocode = lib.mkDefault config.hardware.enableRedistributableFirmware;

  # Enable Flatpak support
  services.flatpak.enable = true;

  ## Base config programs.
  programs = {
    # Enable Wireshark
    wireshark = {
      enable = true;
    };
  };

  # KDE Wallet PAM integration for unlocking the default wallet on login
  security.pam.services."sddm".kwallet.enable = true;

  ## System settings and services.
  mySystem = {
    purpose = "Development";

    ## Desktop Environment
    ## Gnome
    # de.gnome.enable = true;
    ## KDE
    de.kde.enable = true;

    ## Games
    games.steam.enable = true;

    ## System config
    system = {
      motd.networkInterfaces = [ "wlp1s0" ];
      fingerprint-reader-on-laptop-lid.enable = true;
      borg.pika-backup.enable = true;
    };

    framework_wifi_swap.enable = true;
    security._1password.enable = true;
  };
}
