---
# go-task runner file - rest of config in .taskfiles/**.*.yaml
version: "3"

includes:
  sops:
    taskfile: ".taskfiles/sops"
    dir: .taskfiles/sops
  pre:
    taskfile: ".taskfiles/pre-commit"
    dir: "{{.ROOT_DOR}}"

tasks:
  default:
    silent: true
    cmds:
      - task -l

  lint:
    desc: Run statix lint
    cmds:
      - statix check .

  check:
    desc: Check project files
    cmds:
      - task: lint
      - task: pc-run

  format:
    desc: Check project files
    cmds:
      - nixpkgs-fmt {{.ROOT_DIR}}
