{
  imports = [
    ./borgmatic
    ./bind
    ./dnsmasq
    ./forgejo
    ./haproxy
    ./libvirt-qemu
    ./matchbox
    ./nginx
    ./nix-index-daily
    ./onepassword-connect
    ./podman
    ./prowlarr
    ./qbittorrent
    ./radarr
    ./reboot-required-check.nix
    ./sabnzbd
    ./sanoid
    ./sonarr
    ./syncthing
    ./unpackerr
    ./zfs-nightly-snap
  ];
}
