# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{ config, lib, modulesPath, ... }:

{
  imports =
    [
      (modulesPath + "/installer/scan/not-detected.nix")
    ];

  networking.hostId = "2132e3bf";
  networking.hostName = "legiondary";
  boot = {
    initrd.availableKernelModules = [ "xhci_pci" "nvme" "ahci" "usb_storage" "usbhid" "sd_mod" ];
    initrd.kernelModules = [ ];
    kernelModules = [ "kvm-amd" ];
    extraModulePackages = [ ];
  };

  fileSystems =
    {
      "/" =
        {
          device = "zroot/root";
          fsType = "zfs";
        };

      "/nix" =
        {
          device = "zroot/nix";
          fsType = "zfs";
        };

      "/var" =
        {
          device = "zroot/var";
          fsType = "zfs";
        };

      "/home" =
        {
          device = "zroot/home";
          fsType = "zfs";
        };
    };

  # fileSystems."/boot" =
  #   { device = "/dev/disk/by-uuid/E532-B74A";
  #     fsType = "vfat";
  #     options = [ "fmask=0022" "dmask=0022" ];
  #   };

  swapDevices = [ ];

  hardware.cpu.amd.updateMicrocode = lib.mkDefault config.hardware.enableRedistributableFirmware;

  # System settings and services.
  mySystem = {
    purpose = "Development";
    system.motd.networkInterfaces = [ "eno1" "wlp4s0" ];
  };
}
